# Generated by Django 4.2.24 on 2025-09-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_edited_at_message_file_message_file_name_and_more'),
    ]

    operations = [
    ]
